development:
  adapter: postgresql
  encoding: unicode
  database: pgdm_development
  pool: 5
  host: localhost
  username: rails
  password: rails
test:
  adapter: postgresql
  encoding: unicode
  database: pgdm_test
  pool: 5
  host: localhost
  username: rails
  password: rails

production:
  adapter: postgresql
  encoding: unicode
  database: pgdm_production
  pool: 5
  username: rails
  password: rails